displayName=Minion Info
author=Enriath
support=https://github.com/Enriath/external-plugins/tree/minion-info
description=See Minion settings at a glance, similar to an RS3 Tooltip
tags=leagues,demonic,pacts,demonic pacts,minion,tooltip,information,loot,looting,aoe,follow
plugins=io.enriath.minioninfo.MinionInfoPlugin
build=standard